"""
Wiki README.md template
Ported from obsidian-llm-wiki src/templates/readme-md.ts
"""

from __future__ import annotations

from datetime import date


def generate_readme_md(config: dict) -> str:
    """Generate the content of README.md for the wiki vault.

    Parameters
    ----------
    config : dict
        Must contain keys: vault_name (str), wiki_root (str).

    Returns
    -------
    str
        The full markdown content for README.md.
    """
    vault_name: str = config["vault_name"]
    wiki_root: str = config["wiki_root"]
    _ = wiki_root  # kept for API parity with the TypeScript version

    today = date.today().isoformat()

    return f"""# {vault_name} — LLM Wiki

> 知识编译系统：将原始资料编译为结构化的双向链接知识库

## 架构

```
raw/  ──[LLM 编译]──>  wiki/
(源文件, 只读)          (结构化知识, LLM 维护)
```

## 目录

| 目录 | 说明 | 权限 |
|------|------|------|
| `raw/` | 原始源文件 | 人类可读写，LLM 只读 |
| `wiki/summaries/` | 源文件摘要 | LLM 维护 |
| `wiki/concepts/` | 概念页面 | LLM 维护 |
| `wiki/entities/` | 实体页面 | LLM 维护 |
| `wiki/methods/` | 方法页面 | LLM 维护（需质量门控） |
| `wiki/comparisons/` | 对比分析 | LLM 维护 |
| `wiki/analysis/` | 深度分析 | LLM 维护 |
| `wiki/indexes/` | 索引和日志 | LLM 维护 |

## 使用方式

通过 OpenCode MCP Server 操作：

1. **初始化**: `wiki_init`
2. **摄入知识**: 将文件放入 `raw/`，调用 `wiki_ingest`
3. **查询知识**: `wiki_query`
4. **健康检查**: `wiki_lint`

## 双向链接

所有 wiki 页面使用 Obsidian `[[wikilink]]` 格式互相关联，支持：
- 正向链接（当前页面引用了谁）
- 反向链接（谁引用了当前页面）
- 知识图谱可视化

## 规则

- `raw/` 目录下的文件 **绝对不可修改**
- `wiki/` 目录由 LLM 维护，人类可浏览但不建议手动编辑
- 每个内容段落必须标注来源
- 方法页面需通过质量门控才能创建

---

*Generated by obsidian-llm-wiki MCP Server | {today}*
"""
